server:
  port: 8080
server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true
spring:
  application:
    name: restaurant-voting-system
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    # ImMemory
    url: jdbc:h2:mem:topjava
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:topjava
    # Absolute path
    #    url: jdbc:h2:C:/projects/bootjava/db/topjava
    #    tcp: jdbc:h2:tcp://localhost:9092/C:/projects/bootjava/db/topjava
    # Relative path form current dir
    #    url: jdbc:h2:./db/topjava
    # Relative path from home
    #    url: jdbc:h2:~/topjava
    #    tcp: jdbc:h2:tcp://localhost:9092/~/topjava
    username: sa
    password:

  cache:
    cache-names: users
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s

logging:
  level:
    root: INFO
    ru.kortov.topjava: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

springdoc.swagger-ui.path: /

management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    health:
      show-details: always
      show-components: always
